### ISSUE TITLE
支持rpc中生成缓存的时候在key前面自定义参数

### ISSUE THREAD

**Issue by fuckqqcom** [jzero-io/jzero#11]
如题,我也魔改了一版本zero，一直在用，因为zero中redis不支持设置db，因为采用的是在生成代码的时候,加入一个业务key进去做了区分；
另外有交流微信群吗

**Comment by jaronnie** [comment]
我这个不会改 go-zero 以及 goctl 的源码。只是对其进行一个封装，更加便利的使用，有兴趣可以一起扩展。目前我在公司已经在使用这个工具了，感觉还 ok. 有兴趣可以试试看，一起讨论！交流群我现在创建一下，加一下我的微信: jaronnie

**Comment by jaronnie** [comment]
已支持. https://github.com/jzero-io/jzero/commit/d093fe3f5b3234b3b1e6bebeca302b5113f31a24
