### ISSUE TITLE
env

### ISSUE THREAD

**Issue by liushun-ing** [jzero-io/jzero#120]

**Comment by liushun-ing** [comment]
<img width="771" alt="screenshot2024-12-02 10 49 29" src="https://github.com/user-attachments/assets/726f1d15-493e-4b62-922e-da0f01f37cf6">
<img width="346" alt="screenshot2024-12-02 10 49 43" src="https://github.com/user-attachments/assets/d915497a-e4be-4c02-a9a1-59120b590dad">
<img width="1057" alt="screenshot2024-12-02 10 49 55" src="https://github.com/user-attachments/assets/cbc37840-fb15-4fc5-9132-eec0339f5c97">
如图，配置不生效

**Comment by jaronnie** [comment]
${JZERO_GEN.HOOKS.BEFORE}
