### ISSUE TITLE
proto validator希望支持自定义错误message

### ISSUE THREAD

**Issue by WulaSilver** [jzero-io/jzero#32]
比如lte:1000，目前不能自己定义当发生这个错误时的message

**Comment by jaronnie** [comment]
https://github.com/bufbuild/protoc-gen-validate/issues/74

**Comment by jaronnie** [comment]
官方不支持, fork 一个进行维护

**Comment by jaronnie** [comment]
https://github.com/jzero-io/protoc-gen-validate
