### ISSUE TITLE
Add a simple Message Queue example

### ISSUE THREAD

**Issue by gedw99** [jzero-io/jzero#60]
I think it would be great to have an example that use the queue from https://github.com/zeromicro/go-queue/blob/master/natsq/consumer.go

I looked in https://github.com/jzero-io/examples, but found now.

NATS is much better than Kafka, because you can embed the server or not. SO it's much easier for a golang team to run.

It has lot of other advantages.

**Comment by jaronnie** [comment]
Yes, I have also used nats, which is very lightweight and has no usage burden. jzero examples repo currently only has framework-level examples. If you use nats in jzero, I also look forward to your submission of PR on how to use nats in jzero.

**Comment by jaronnie** [comment]
Do you use https://github.com/zeromicro/go-queue/tree/master/natsq to integrate nats? I think the framework is not too restrictive. You can run the demo without any worries.

**Comment by jaronnie** [comment]
What you mean is that you want to use nats to replace the key/value usage scenario of redis. go-zero supports the use of redis, but it does not support directly switching to nats by just modifying the configuration. To get it, you need to rewrite a package to replace it. You can refer to how k3s replaces nats.

**Comment by jaronnie** [comment]
In addition, do you also want to replace mysql with sqlite? I think it is supported in jzero now.

**Comment by jaronnie** [comment]
Is it possible to write a NATS library to implement the common functions of redis? There should be an open source library for this part.

**Comment by jaronnie** [comment]
Yes, but the code implementation seems to be strongly bound to redis, and it is still difficult to fully implement the replacement you want.

**Comment by jaronnie** [comment]
You can try to fork go-zero and implement nats store. jzero can replace go-zero with your forked version through template feature to generate code

**Comment by jaronnie** [comment]
yes, I have the author's contact information, but I also wanted to include some plugins in the official repository before, but they refused. So I think it is difficult to include nats in the core repo. You need to have a good reason to convince them, or if they have no plan, it will be difficult.

**Comment by jaronnie** [comment]
okay
